id: d6_piwik_user_settings
label: Piwik user settings
migration_tags:
  - Drupal 6
source:
  plugin: d6_user
  constants:
    key: user_account_users
    module: piwik
process:
  uid: uid
  key: 'constants/key'
  module: 'constants/module'
  settings:
    # Based on skip_row_if_not_set
    plugin: piwik_skip_row_if_not_set
    key: custom
    module: piwik
    source: data
destination:
  plugin: user_data
migration_dependencies:
  required:
    - d6_user
