.base: &base
  roles: app
  branch: develop
  user: sddt
  hostname: syddjursdetdertaeller.dk

prod:
  <<: *base
  stage: production
  deploy_path: /data/www/vhost/syddjurs_deployer.dk
  branch: master
  hostname: 81.95.247.101

staging:
  <<: *base
  stage: staging
  deploy_path:  /data/www/vhost/syddjurs_deployer.dk
  hostname: 81.95.247.102